### ISSUE TITLE
스트래티지 패턴(전략 패턴) 처럼 구현하셨는데...

### ISSUE THREAD

**Issue by Mommoo** [inthej/McDonaldKiosk#9]
스트래티지 패턴은, 써야 할 상황이 있습니다.

현재 상황은 알고리즘이 다른게 아니라, 알고리즘 자체는 같고 '데이터만' 조금씩 다른 상황입니다.

이는 오히려, '데이터'만 다르면 매개변수를 받아 호출 하는게 낫지, 이런식으로

인터페이스화 하는건 바람직 하지 않습니다. (상황을 모르고 쓰는건 독입니다.) 

'디자인 패턴'은 무척 중요하고 꼭 학습을 해야하지만, 아직은 시기상조인거 같습니다.

이미 고친건 어쩔 수 없고,  새로운 개념을 추가 하지마시고, 기존있던 코드 정리 부터 하셨으면 합니다.

(저번에 말씀드렸던 MenuPage를 고쳐보셨으면 합니다.)

6월 말까지는 정리 작업을 목표로 삼으세요.

연습량이 아직 부족합니다.

**Comment by inthej** [comment]
이게 패턴 이군요. 패턴을 따로 찾아서 학습한 건 아니고.
개인 repository의 OOP의 연습 예제의 '추상화' 학습한 걸 다지는 목적으로 프로젝트에 사용해 보았습니다. 
캡슐화 pull request 받기 이전부터 시도했다가 안됐던 건데 어제 생각이 정리되는 시점이라 코딩을 한번 해보았습니다. 무리네요. 그냥 몸 상태 회복에 전념 해야 할듯합니다. 저도 코딩하면서 '이걸 여기에 적용해야 하나?'라는 생각은 하였지만 계속 실패했던 거라 찝찝해서 추상화 훈련 겸해서 일단은 큰 생각 없이 코딩을 하였습니다. 알려주셨던 인터페이스의 활용 목적으로는 적합하지 않다고 봅니다.

말씀 주셨던 내용처럼 현제 코드 정리와 캡슐화를 가장 중요하게 생각하고 있습니다. 저에게 가장 부족하다고 생각되는 표현부터 올바르게 잡으려고 하고있습니다. 조언을 받은 이후 제대로 된 표현을 하여야 역할이 명확해져서 정체성이 분명해지고 시간 절약 및 좋은 프로그래밍을 할 수 있다고 느꼈기 때문입니다. 찝찝하던거 마무리하였으니 어떻게 하면 더 잘 표현하고 올바른 클래스의 구성을 가지는지 부족한 걸 채우는 단계로 남은 6월을 준비하도록 하겠습니다.

개인 사정으로 코딩을 못하는 상황이라고 말씀드렸는데 신경 써서 확인해주시고 조언까지 해주셔서 감사합니다.
이번에 말씀 주신 내용도 염두에 두도록 하겠습니다. 휴식을 통하여 몸 상태 회복한 이후 연습량 슬슬 올리도록 하겠습니다.

그래도 완료도 하고 몰랐던 조언도 받았으니 의미 있었다고 봅니다.

**Comment by Mommoo** [comment]
몸도 안좋으신데도 고생하십니다.

개인 연습은, 로컬 커밋으로 관리 하시고 저에게 확인 받아야할 것만 온라인 저장소에 커밋을 해주시면

더 좋을거 같습니다.  

뭐든 좋습니다. 이번에 하신것도 의미가 있다고 봅니다. 저는, 쓸때없는 연습은 없어요.

패턴을 배우시지도 않았는데, 스트래티지 패턴처럼 생각을 하신 것은, 그러한 설계방향이

맞다고 생각하셨기 때문이지요.

이처럼, '디자인 패턴'은 개발자들이 설계를 이리 저리 고치고, 생각하고, 반영하고 하면서

깨닫거나 얻은 좋은 설계를 마치 교과서처럼 제공하는것 뿐입니다.

때문에, 좋은코드를 짜려고 계속 노력한다면 '디자인 패턴'에서 제시하는 설계 방향과 맞을 경우가 많습니다.

다만, 짜주신 코드를 보기도 하였고 평소에 형이 저에게 주시는 느낌은

아직 인터페이스의 느낌을 잘 모르신다는 겁니니다.

인터페이스는 정리용도로 사용하면 안됩니다.

서로 다른 무언가를 간단한 다리(인터페이스)를 통해서 서로 통하게 하는것이 되어야 하는데,

사실상 짜주신건 단순한 인간이 보기 위한 정리에 가깝습니다.

그러한 인터페이스는 의미가 없다는걸 깨달으셔야 합니다.


벌써6월 중순이 다와가네요. 몸조리 잘하세요.

**Comment by inthej** [comment]
네, 말씀대로 확인받을 저장소만 운영하도록 하겠습니다. 저러한 인터페이스 용도도 아니였군여. 
캡슐화, 추상화를 잘해야 할듯한데 둘다 너무 어려운거 같습니다. 빨리 낫도록 하겠습니다. 좋은 말씀 감사합니다.
